trigger:
- main

pool:
  name: MyAgentPool

steps:
- task: Docker@2
  displayName: Build and Push Image
  inputs:
    containerRegistry: 'gebreluademoacr'
    repository: 'devops-demo'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: |
      v1
